channels:
  - pytorch
  - openeye
  - conda-forge
  - defaults
dependencies:
  - black=23.3.0
  - charset-normalizer=2.0.4
  - cudatoolkit=11.3.1
  - isort=5.9.3
  - numpy-base=1.23.5
  - openeye-toolkits=2021.2.0
  - optuna=3.1.0
  - python=3.8.12
  - pytorch=1.11.0
  - s3fs=2023.4.0
  - tqdm=4.64.1
  - yaml=0.2.5
  - pip:
    - git+https://github.com/katsura-jp/pytorch-cosine-annealing-with-warmup
    - cycler==0.11.0
    - fastparquet==2023.2.0
    - hydra-core==1.3.2
    - hydra-optuna-sweeper==1.2.0
    - matplotlib==3.7.0
    - omegaconf==2.3.0
    - pandas==1.5.3
    - pyarrow==11.0.0
    - pytorch-lightning==1.9.3
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - tensorboard==2.11.2
