seed: 0
dataloaders:
  _target_: training.build_dataloaders
  dataset:
    _target_: dataset.SupervisedGraphDataset
    data_path: data/chembl20/chembl20.csv
    cmpd_col: smiles
    cmpd_col_is_inchikey: false
    pad_length: 500
  splits:
    train: data/chembl20/chembl20-frac1-split1-train.csv
    val: data/chembl20/chembl20-split1-val.csv
    test: data/chembl20/chembl20-split1-test.csv
  batch_size: 128
  num_workers: 4
model:
  _target_: model.LightningGGNN
  n_edge: 1
  in_dim: 75
  n_conv: 7
  fc_dims:
  - 1024
  - 1310
  p_dropout: 0.1
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  num_nodes: 1
  precision: 32
  max_epochs: 1000
  min_epochs: 50
  check_val_every_n_epoch: 1
  callbacks:
  - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: val/auprc
    mode: max
    patience: 20
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/auprc
    mode: max
    save_top_k: 2
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ./
    name: chembl20_fromscratch
test_model:
  _target_: model.LightningGGNN.load_from_checkpoint
  _args_:
  - 
  n_edge: ${model.n_edge}
  in_dim: ${model.in_dim}
  n_conv: ${model.n_conv}
  fc_dims: ${model.fc_dims}
  p_dropout: ${model.p_dropout}
