seed: 0
dataloaders:
  _target_: training.build_dataloaders
  dataset:
    _target_: dataset.SupervisedGraphDataset
    data_path: 
    cmpd_col: Metadata_InChI
    cmpd_col_is_inchikey: true
    pad_length: 250
  splits:
    train: data/jump/jump-compound-split-0-train.csv
    val: data/jump/jump-compound-split-0-val.csv
    test: data/jump/jump-compound-split-0-test.csv
  batch_size: 1024
  num_workers: 48
model:
  _target_: model.LightningGGNNRegression
  n_edge: 1
  in_dim: 75
  n_conv: 7
  fc_dims:
  - 1024
  - 3475
  p_dropout: 0.1
optimizer:
  _target_: torch.optim.Adam
  lr: 1.0e-05
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  num_nodes: 1
  precision: 32
  max_epochs: 1000
  min_epochs: 10
  check_val_every_n_epoch: 1
  callbacks:
  - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: val/mse
    mode: min
    patience: 10
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/mse
    mode: min
    save_top_k: 2
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: /hpc/scratch/hdd1/cn366187/clip-joint-embedding/tb_logs_ggnn_jump_lr00001
    name: ggnn_jump_seed_0_split_0
test_model:
  _target_: model.LightningGGNN.load_from_checkpoint
  _args_:
  - tb_logs/baseline_ggnn/version_12/checkpoints/epoch=171-step=4815.ckpt
  n_edge: ${model.n_edge}
  in_dim: ${model.in_dim}
  n_conv: ${model.n_conv}
  fc_dims: ${model.fc_dims}
  p_dropout: ${model.p_dropout}
